# Generated by Django 3.0.5 on 2020-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200409_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='Coloring_Page',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='image',
            name='Original_Image',
            field=models.ImageField(default=None, upload_to='original_images'),
            preserve_default=False,
        ),
    ]
